### PR TITLE
Support for tree collections

### PR DESCRIPTION
**Pull request by jimallman**
This is a major refactoring of peyotl to support tree collections and other simple content types in sharded docstores. It introduces new "type-aware" base classes for docstores and shards, so that we can isolate the special requirements and business rules for each document type while keeping common behavior.

This is currently working on **devtree** and [passing all Travis tests in python 2 and python 3](https://travis-ci.org/OpenTreeOfLife/peyotl/builds/60314077). Note that there are some required modifications to server-configuration files, mostly to accommodate the new minor doc-types. Also companion branches  for repos **phylesystem-api** (support-tree-collection) and **opentree** (support-tree-collections). Pull requests for these will follow shortly.

There's a lot of documentation still to come, but hopefully this is good enough for a code review.

Finally, while this doesn't include full support for "favorites", I've laid the groundwork in several areas. This type will mirror the `collections` package and tests, with modified business rules, nomenclature, and tests.

### CODE REVIEW

**Comment by jimallman** [comment]
Hm, it seems python 3.4 is unhappy with something in oti. This is unlikely to be related to the changes in this branch.

**Comment by jimallman** [comment]
I'm investigating the current Travis build errors, and it seems some are due to new restrictions in the APIs. Specifically, this call is part of 

```bash
curl -vv -X POST http://devapi.opentreeoflife.org/v2/tree_of_life/subtree \
    -H "Content-Type: Application/json" \
    -d '{"node_id": "1", "tree_id": "opentree3.0"}'
* Hostname was NOT found in DNS cache
*   Trying 128.30.16.133...
* Connected to devapi.opentreeoflife.org (128.30.16.133) port 80 (#0)
> POST /v2/tree_of_life/subtree HTTP/1.1
> User-Agent: curl/7.37.1
> Host: devapi.opentreeoflife.org
> Accept: */*
> Content-Type: Application/json
> Content-Length: 42
>
* upload completely sent off: 42 out of 42 bytes
< HTTP/1.1 400 Bad Request
< Date: Sat, 18 Jul 2015 03:57:35 GMT
* Server Jetty(6.1.25) is not blacklisted
< Server: Jetty(6.1.25)
< Content-Length: 915
< Content-Type: application/json; charset=UTF-8
< Access-Control-Allow-Origin: *
< Connection: close
<
{
  "message" : "Requested tree is larger than currently allowed by this service (25000 tips). For larger trees, please download the full tree directly from: http://files.opentreeoflife.org/trees/",
  "exception" : "IllegalArgumentException",
  "fullname" : "java.lang.IllegalArgumentException",
  "stacktrace" : [ "opentree.plugins.tree_of_life.subtree(tree_of_life.java:402)", "java.lang.reflect.Method.invoke(Method.java:497)", "org.neo4j.server.plugins.PluginMethod.invoke(PluginMethod.java:57)", "org.neo4j.server.plugins.PluginManager.invoke(PluginManager.java:168)", "org.neo4j.server.rest.web.ExtensionService.invokeGraphDatabaseExtension(ExtensionService.java:300)", "org.neo4j.server.rest.web.ExtensionService.invokeGraphDatabaseExtension(ExtensionService.java:122)", "java.lang.reflect.Method.invoke(Method.java:497)", "org.neo4j.server.rest.security.SecurityFilter.doFilter(SecurityFilter.java:112)" ]
* Closing connection 0
}
```

The basic error message is this:
```"Requested tree is larger than currently allowed by this service (25000 tips). For larger trees, please download the full tree directly from: http://files.opentreeoflife.org/trees/"```

This [tree-size limit](https://github.com/OpenTreeOfLife/treemachine/blob/2214f2ae435991f968c5ad555a78f42247a7b895/src/main/java/opentree/plugins/tree_of_life.java#L399-L404) comes from a change in treemachine [made by @josephwb on May 14, 2015](https://github.com/OpenTreeOfLife/treemachine/commit/1bc6c049ca510517be75905babaf6b02d81990e8?w=1).

For now, I'm modifying the `testSynthTree` test to expect an `HTTPError` instead of the previously expected `ValueError`. @mtholder, does this leave an important gap in testing?

**Comment by jimallman** [comment]
@mtholder, I've modified some tests to conform to [this treemachine change](https://github.com/OpenTreeOfLife/treemachine/commit/cb36de438ac26a58bebb7f10aa8d3a1609da0dde), the renaming of `"subtree"` to `"newick"` in the output of `induced_subtree`.

**Comment by jimallman** [comment]
@jar398, with some recent changes (some of which could be cherry-picked to `master` branch), this branch now passes in Travis.

**Comment by mtholder** [comment]
Yay! thanks, @jimallman

**Pull request merged**
