### PR TITLE
Amendment test fixes

### PR DESCRIPTION
**Pull request by jimallman**
This fixes amendment-related unit tests, including maintainer tests and those testing against remote (production) web services. Thanks to @mtholder for spotting these failures!

### CODE REVIEW

**Comment by jimallman** [comment]
**Reminder:** To run all the tests covered, you'll need to update the local (mini_*) repositories like so:
```bash
cd peyotl
rm -rf peyotl/test/data/template_mini_par/
bash ./bootstrap.sh
bash ./maintainer-tests.sh
```

To test against remote (production) web services, you'll need to set a variable:
```bash
export RUN_WEB_SERVICE_TESTS=1;bash maintainer-test.sh
```

**Comment by jimallman** [comment]
@kcranston, Do the changes above satisfy your request for easy post-deployment testing of our APIs? I was thinking about adding to [the curation-app tests described here](https://github.com/OpenTreeOfLife/opentree/blob/master/TESTS.md), but those target web2py URLs served by the web-app.

**Comment by kcranston** [comment]
Seems fine to me. Thanks!

**Comment by jimallman** [comment]
@mtholder This PR should fix the amendment tests (and a few other nits I found along the way). Please merge and close if this works for you.

**Comment by mtholder** [comment]
oddly enough those tests are not working for me. I'll try to figure out why.

**Comment by mtholder** [comment]
For example:

``` 
$ python peyotl/test/test_amendments_api.py
E.EE..EE..
======================================================================
ERROR: testAmendmentList (__main__.TestTaxonomicAmendmentsAPI)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "peyotl/test/test_amendments_api.py", line 55, in testAmendmentList
    al = taa.amendment_list
  File "/home/mtholder/Documents/projects/ot/peyotl/peyotl/api/amendments_api.py", line 84, in amendment_list
    return self.docstore_obj.get_amendment_ids()
  File "/home/mtholder/Documents/projects/ot/peyotl/peyotl/api/amendments_api.py", line 52, in docstore_obj
    self._docstore_obj = TaxonomicAmendmentStore()
  File "/home/mtholder/Documents/projects/ot/peyotl/peyotl/amendments/amendments_umbrella.py", line 357, in TaxonomicAmendmentStore
    infrastructure_commit_author=infrastructure_commit_author)
  File "/home/mtholder/Documents/projects/ot/peyotl/peyotl/amendments/amendments_umbrella.py", line 112, in __init__
    self._growing_shard._determine_next_ott_id()
AttributeError: 'NoneType' object has no attribute '_determine_next_ott_id'

======================================================================
ERROR: testCreateAmendmentRemote (__main__.TestTaxonomicAmendmentsAPI)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "peyotl/test/test_amendments_api.py", line 72, in testCreateAmendmentRemote
    al = taa.amendment_list
  File "/home/mtholder/Documents/projects/ot/peyotl/peyotl/api/amendments_api.py", line 83, in amendment_list
    return self._remote_amendment_list()
  File "/home/mtholder/Documents/projects/ot/peyotl/peyotl/api/amendments_api.py", line 141, in _remote_amendment_list
    return self.json_http_get(uri)
  File "/home/mtholder/Documents/projects/ot/peyotl/peyotl/api/wrapper.py", line 428, in json_http_get
    return self._do_http(url, 'GET', headers=headers, params=params, data=None, text=text)
  File "/home/mtholder/Documents/projects/ot/peyotl/peyotl/api/wrapper.py", line 468, in _do_http
    resp.raise_for_status()
  File "/home/mtholder/Documents/projects/ot/peyotl/env/local/lib/python2.7/site-packages/requests/models.py", line 844, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 404 Client Error: NOT FOUND for url: https://api.opentreeoflife.org/v3/amendments/amendment_list

======================================================================
ERROR: testDeleteAmendmentRemote (__main__.TestTaxonomicAmendmentsAPI)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "peyotl/test/test_amendments_api.py", line 141, in testDeleteAmendmentRemote
    al = taa.amendment_list
  File "/home/mtholder/Documents/projects/ot/peyotl/peyotl/api/amendments_api.py", line 83, in amendment_list
    return self._remote_amendment_list()
  File "/home/mtholder/Documents/projects/ot/peyotl/peyotl/api/amendments_api.py", line 141, in _remote_amendment_list
    return self.json_http_get(uri)
  File "/home/mtholder/Documents/projects/ot/peyotl/peyotl/api/wrapper.py", line 428, in json_http_get
    return self._do_http(url, 'GET', headers=headers, params=params, data=None, text=text)
  File "/home/mtholder/Documents/projects/ot/peyotl/peyotl/api/wrapper.py", line 468, in _do_http
    resp.raise_for_status()
  File "/home/mtholder/Documents/projects/ot/peyotl/env/local/lib/python2.7/site-packages/requests/models.py", line 844, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 404 Client Error: NOT FOUND for url: https://api.opentreeoflife.org/v3/amendments/amendment_list

======================================================================
ERROR: testLocalSugar (__main__.TestTaxonomicAmendmentsAPI)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "peyotl/test/test_amendments_api.py", line 184, in testLocalSugar
    self._do_sugar_tests(taa)
  File "peyotl/test/test_amendments_api.py", line 47, in _do_sugar_tests
    a = taa.get('additions-5861452-5861452')
  File "/home/mtholder/Documents/projects/ot/peyotl/peyotl/api/amendments_api.py", line 107, in get
    r = self.get_amendment(amendment_id)
  File "/home/mtholder/Documents/projects/ot/peyotl/peyotl/api/amendments_api.py", line 118, in get_amendment
    json, sha = self.docstore_obj.return_doc(amendment_id) #pylint: disable=W0632
  File "/home/mtholder/Documents/projects/ot/peyotl/peyotl/api/amendments_api.py", line 52, in docstore_obj
    self._docstore_obj = TaxonomicAmendmentStore()
  File "/home/mtholder/Documents/projects/ot/peyotl/peyotl/amendments/amendments_umbrella.py", line 357, in TaxonomicAmendmentStore
    infrastructure_commit_author=infrastructure_commit_author)
  File "/home/mtholder/Documents/projects/ot/peyotl/peyotl/amendments/amendments_umbrella.py", line 112, in __init__
    self._growing_shard._determine_next_ott_id()
AttributeError: 'NoneType' object has no attribute '_determine_next_ott_id'

======================================================================
ERROR: testModifyAmendmentRemote (__main__.TestTaxonomicAmendmentsAPI)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "peyotl/test/test_amendments_api.py", line 111, in testModifyAmendmentRemote
    raise_HTTPError_with_more_detail(err)
  File "peyotl/test/test_amendments_api.py", line 25, in raise_HTTPError_with_more_detail
    raise ValueError("{e}, details: {m}".format(e=err, m=details))
ValueError: 404 Client Error: NOT FOUND for url: https://api.opentreeoflife.org/v3/amendment/additions-0000000-0000000, details: {"description": "Amendment 'additions-0000000-0000000' GET failure", "error": 1}

----------------------------------------------------------------------
Ran 10 tests in 3.295s

FAILED (errors=5)
```

**Comment by jar398** [comment]
I don't see any handling of the allowwrite flag. Maybe I missed it. (It's
important to be able to run the read tests on production without running
the write tests.)

**Comment by jimallman** [comment]
@jar398 These tests are not covered by germinator's ws-test runner. I agree that the `allowwrite` switch would be useful here, but it will take some fiddling as peyotl uses a different approach to configuration; see [peyotl/default.conf](https://github.com/OpenTreeOfLife/peyotl/blob/3c32582e16be9dcf1029ce3d6481cdb09444890a/peyotl/default.conf) for settings related to logging and API base URLs.

[There is a `get_test_config` method](https://github.com/OpenTreeOfLife/peyotl/search?utf8=%E2%9C%93&q=get_test_config) that looks for a local `test.conf`, but it's not called within peyotl.

**Comment by jimallman** [comment]
@mtholder Did you [clobber and rebuild the mini_* repos](https://github.com/OpenTreeOfLife/peyotl/pull/153#issuecomment-238691819) as described above? Removing my local mini_amendments repo gave me one of your reported errors, since no shards could be found:
```
  File "/home/mtholder/Documents/projects/ot/peyotl/peyotl/amendments/amendments_umbrella.py", line 112, in __init__
    self._growing_shard._determine_next_ott_id()
AttributeError: 'NoneType' object has no attribute '_determine_next_ott_id'
```

**Comment by mtholder** [comment]
hmm. I thought that (via inspection of the script and bash commands) I had done the equivalent. But I'll give clobbering them a shot.

**Comment by jimallman** [comment]
@mtholder please give these tests another go (against devapi.opentreeoflife.org). I've added the expected `/v3/amendments/amendment_list` to phylesystem-api, so if your local mini-* repos are in place, all the tests should now pass.

**Comment by mtholder** [comment]
hmm part of the problem is that it was finding a version of the mini_amendments dir that I was not expecting. It was old so it lacked the `next_ott_id.json` file. I'm still getting some other failures, though. I'll report back soon.

**Comment by mtholder** [comment]
I'm still getting failures on the API tests. For instance the first one fails with:


    Traceback (most recent call last):
      File "peyotl/test/test_amendments_api.py", line 84, in testCreateAmendmentRemote
        commit_msg)
      File "/home/mtholder/Documents/projects/ot/peyotl/peyotl/api/amendments_api.py", line 163, in post_amendment
        data=anyjson.dumps({'json': json}))
      File "/home/mtholder/Documents/projects/ot/peyotl/peyotl/api/wrapper.py", line 444, in json_http_post
        return self._do_http(url, 'POST', headers=headers, params=params, data=data, text=text)
      File "/home/mtholder/Documents/projects/ot/peyotl/peyotl/api/wrapper.py", line 468, in _do_http
        resp.raise_for_status()
      File "/home/mtholder/Documents/projects/ot/peyotl/env/local/lib/python2.7/site-packages/requests/models.py", line 844, in raise_for_status
        raise HTTPError(http_error_msg, response=self)
    HTTPError: 400 Client Error: BAD REQUEST for url: https://devapi.opentreeoflife.org/v3/amendment/TODO-2?auth_token=SUPPRESSED&commit_msg=Test+of+creating+amendments+via+API+wrapper


where `SUPPRESSED` in the message is actually my GitHub OAuth token (which is in my env when I run the script)

which calls the equivalent of:

    curl -X POST -H "Content-Type":"application/json" -H "Accept":"application/json" https://devapi.opentreeoflife.org/v3/amendment/TODO-2 --data '{"json": {"taxa": [], "curator": {"login": "", "name": ""}, "study_id": "ot_999999", "user_agent": "", "date_created": "2016-08-25", "id": ""}}'

That cURL call is failing with the messagte `{"description": "invalid amendment ID (TODO-2) provided", "error": 1}`

**Comment by jimallman** [comment]
@mtholder, as discussed I've disabled the CRUD tests for amendments, and added alternate ids to support testing against the dev or production repos. Please re-try these tests at your convenience. 

_NOTE that you'll probably want to update your peyotl config to match the latest here, since I've added [an explicit entry for the amendments API domain](https://github.com/OpenTreeOfLife/peyotl/blob/amendment-test-fixes/peyotl/default.conf#L9)._

**Pull request merged**
