### PR TITLE
Issue 122

### PR DESCRIPTION
**Pull request by mtholder**
fixes https://github.com/OpenTreeOfLife/peyotl/issues/122
new test, testMimicPhylesystemExport, will fail if we regress.

### CODE REVIEW

**Comment by snacktavish** [comment]
As I understand it, this will return an empty string if NEXUS is requested, and tree is not in study. But that doesn't seem consistent with returning ' subresource "tree/tree999" not found in study "2647" ' if JSON is requested for the same tree. (from https://github.com/OpenTreeOfLife/feedback/issues/61) Is this true/the behavior we want?

**Comment by jar398** [comment]
I haven't merged this to production because the travis build failed.

**Comment by mtholder** [comment]
yeah the peyotl tests are failing because of changes to treemachine API and bugs in oti. Ideally we'd have some stable services endpoint so that this would not happen. I could move the web-service dependent tests out of the peyotl test suite (and into germinator?), but I do like to know when those fail.

**Comment by jar398** [comment]
I trust that the OTI bugs have been reported, and that if treemachine behavior is different from what's documented, then a documentation bug has been reported.

**Pull request merged**
